language: node_js

node_js:
  - "0.10"

matrix:
  fast_finish: true

after_success:
  - |
      npm install coveralls
      cat coverage/lcov.info | node_modules/.bin/coveralls && echo "Coverage data was sent to coveralls!"
